/**
 * Map every single-country source to its ISO country code. The sink reads
 * this when a `ScrapedProfessional` does not set `country` explicitly. This
 * is how we keep ~150 single-country sources untouched while still fixing
 * the cross-country slug-collision bug that mis-attributed ~5,500 rows.
 *
 * Multi-country sources (google_places, osm, overture, wikidata, gleif,
 * paginas_amarillas, habitissimo, manual, cronoshare, competitor-*…) are
 * deliberately omitted — they MUST set `record.country` per row, otherwise
 * an MX `guadalajara` row silently lands on the ES `guadalajara`.
 */
export const SOURCE_COUNTRY: Record<string, "ES" | "CA" | "US" | "FR" | "MX"> = {
  // ES — Spain
  ccaa_registry: "ES",
  "cgcoo-opticos": "ES",
  "cgn-notariado": "ES",
  "cgpe-procuradores": "ES",
  colegio: "ES",
  com_gipuzkoa: "ES",
  com_madrid: "ES",
  com_zaragoza: "ES",
  "comb-barcelona": "ES",
  "datos-gob-es": "ES",
  "dgt-itv-es": "ES",
  doctoralia: "ES",
  "farmaceuticos-es-guardia": "ES",
  "guiadentistas-es": "ES",
  "habitissimo-es": "ES",
  "open-data-bcn-locales": "ES",
  "rasic-talleres-cat": "ES",
  vucolvet: "ES",

  // FR — France
  "ademe-rge": "FR",
  "annuaire-sante-ans": "FR",
  "architectes-fr": "FR",
  "auto-ecoles-fr": "FR",
  "cnb-avocats": "FR",
  "cnop-pharmaciens": "FR",
  finess: "FR",
  "geometres-fr": "FR",
  "oec-fr": "FR",
  "ordre-vet-fr": "FR",
  "prix-controle-technique": "FR",
  "sirene-insee": "FR",

  // MX — Mexico
  "amda-distribuidores": "MX",
  "antad-asociados": "MX",
  "clues-sinais-mx": "MX",
  "cmic-constructoras": "MX",
  "cnbv-entidades": "MX",
  "cnsf-agentes": "MX",
  "cofepris-farmacias": "MX",
  "colegio-notarios-cdmx": "MX",
  "colegios-notarios-mx": "MX",
  "conacem-mx": "MX",
  "conahcyt-snii": "MX",
  "condusef-sipres": "MX",
  "cre-permisionarios": "MX",
  "denue-mx": "MX",
  "doctoralia-mx": "MX",
  "dro-cdmx": "MX",
  "ema-acreditados": "MX",
  "fcarm-arquitectos": "MX",
  "fedmvz-colegios-vet": "MX",
  "ift-rpc-mx": "MX",
  "imcp-colegios-mx": "MX",
  "imss-directorio": "MX",
  "notariado-mx": "MX",
  "padron-ganadero-nacional": "MX",
  "padron-notarios-fed-mx": "MX",
  "profeco-rpca-talleres": "MX",
  "profeco-sancionados": "MX",
  "profepa-verificentros-edomex": "MX",
  "re-franchises-mx": "MX",
  "sat-cpr-mx": "MX",
  "sat-efos-edos": "MX",
  "sedema-verificentros-cdmx": "MX",
  "senasica-mx-vet": "MX",
  siem: "MX",
  "verificacion-edomex": "MX",
  "verificacion-jalisco": "MX",

  // CA — Canada
  "amvic-dealers": "CA",
  apega: "CA",
  "barreau-qc": "CA",
  "cap-psychologists": "CA",
  cmq: "CA",
  "cpm-physio": "CA",
  cpsa: "CA",
  cpsbc: "CA",
  cpsm: "CA",
  cpsnl: "CA",
  "cpsns-ns-physicians": "CA",
  cpso: "CA",
  cpspei: "CA",
  ecra: "CA",
  "engineers-ns": "CA",
  hcra: "CA",
  "industry-ca": "CA",
  "law-society-bc": "CA",
  "lsnb-bar": "CA",
  lso: "CA",
  "lss-saskatchewan": "CA",
  "nsbs-ns": "CA",
  oaa: "CA",
  oaq: "CA",
  odq: "CA",
  "pegnl-nl": "CA",
  rcdso: "CA",
  "scpp-sk-pharmacists": "CA",
  "svma-sk-vets": "CA",
  tsask: "CA",
  tsbc: "CA",
  tssa: "CA",

  // US — United States
  aila: "US",
  "arizona-roc": "US",
  avvo: "US",
  "bar-ca": "US",
  "bar-ny": "US",
  "bar-tx": "US",
  "ca-dca-open-data": "US",
  "cms-pecos": "US",
  "colorado-dora": "US",
  cslb: "US",
  "fl-doh-mqa": "US",
  "florida-dbpr": "US",
  "georgia-plb": "US",
  "hifld-us": "US",
  homeadvisor: "US",
  houzz: "US",
  "illinois-idfpr": "US",
  "louisiana-lslbc": "US",
  "maryland-dllr": "US",
  "massachusetts-dpl": "US",
  "michigan-lara": "US",
  "minnesota-dli": "US",
  "missouri-dpr": "US",
  "nevada-nscb": "US",
  "new-jersey-dca": "US",
  "new-york-dos": "US",
  "north-carolina-lbc": "US",
  npi: "US",
  "ny-sed-professions": "US",
  "nyc-dob": "US",
  "oh-elicense": "US",
  "ohio-elicense": "US",
  "oig-leie": "US",
  "oregon-ccb": "US",
  "pa-pals": "US",
  "pennsylvania-bpoa": "US",
  "tennessee-tdci": "US",
  "texas-tdlr": "US",
  thumbtack: "US",
  "virginia-dpor": "US",
  "washington-li": "US",
  "wisconsin-dsps": "US",
};
